carpark/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('dashboard.urls'), name='dashboard_urls'),
    path('accounts/', include('allauth.urls')),
]

dashboard/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.BookingList.as_view(), name='home'),
    path('booking_creation/', views.BookingCreation.as_view(), name='booking_creation'),
    path('booking_edition/', views.BookingEdition.as_view(), name='booking_edition'),
    path('booking_edition/<str:booking_id>', views.BookingEdition.as_view(), name='booking_edition'),
    path('delete_booking/<str:booking_id>', views.delete_booking, name='delete_booking'),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User


class Booking(models.Model):
    """
    Booking model
    """
    booking_name = models.TextField()
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="dashboard_bookings"
    )
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    notes = models.TextField()
    start_booking_date = models.DateTimeField()
    end_booking_date = models.DateTimeField()
    car_model = models.TextField()
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.author.username

dashboard/forms.py
from .models import Booking
from django import forms
from datetime import datetime
from django.utils import timezone


class BookingForm(forms.ModelForm):
    """
    This class handle the form to show when creating or editing a booking
    """
    class Meta:
        model = Booking
        fields = ('booking_name', 'notes', 'car_model', 'start_booking_date', 'end_booking_date',)
        widgets = {
            'booking_name': forms.TextInput(attrs={
                'maxlength': '100'
            }),
            'car_model': forms.TextInput(attrs={
                'maxlength': '100'
            }),
            'notes': forms.Textarea(attrs={'rows': 5, 'maxlength': '1000'}),
            'start_booking_date': forms.TextInput(attrs={'type': 'datetime-local'}),
            'end_booking_date': forms.TextInput(attrs={'type': 'datetime-local'}),
        }

    def clean(self):
        """
        This function handles some form data validation 
        """
        super(BookingForm, self).clean()

        start_booking_date = self.cleaned_data.get('start_booking_date')
        end_booking_date = self.cleaned_data.get('end_booking_date')

        if start_booking_date.timestamp() < timezone.now().timestamp():
            self._errors['start_booking_date'] = self.error_class(['The start date should be after today'])
        
        if end_booking_date.timestamp() < start_booking_date.timestamp():
            self._errors['end_booking_date'] = self.error_class(['The end date should not be before the start date'])
        
        return self.cleaned_data

dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic, View
from .models import Booking, User
from .forms import BookingForm
from django.contrib import messages


class BookingList(generic.ListView):
    """
    View to display Booking list in the home page
    """

    model = Booking
    template_name = 'index.html'
    paginate_by = 6

    def get_queryset(self):
        """
        Method to filter the bookings by the active user
        """
        try:
            if self.request.user.is_authenticated:

                user = self.request.user
                return Booking.objects.filter(author=user).order_by('-created_on')
            else:
                return Booking.objects.order_by('-created_on')
        except Exception as e:
            print('%s' % e)


class BookingCreation(View):
    """
    View to display and handle Booking creation form
    """
    def get(self, request, *args, **kwargs):

        return render(
            request,
            "booking_creation.html",
            {
                "booking_form": BookingForm()
            },
        )

    def post(self, request, *args, **kwargs):

        queryset = User.objects.filter(username=request.user.username)
        user = get_object_or_404(queryset)

        booking_form = BookingForm(data=request.POST)

        if booking_form.is_valid():
            booking_form.instance.email = request.user.email
            booking_form.instance.name = request.user.username

            booking = booking_form.save(commit=False)
            booking.author = user

            booking.save()

            messages.success(request, 'Your booking has been sent and is awaiting approval')  
            return redirect('home')

        return render(
            request,
            "booking_creation.html",
            {
                "booking_form": booking_form
            },
        )


class BookingEdition(View):
    """
    View to display and handle Booking edition form
    """
    def get(self, request, booking_id, *args, **kwargs):

        booking = get_object_or_404(Booking, id=booking_id)

        return render(
            request,
            "booking_edition.html",
            {
                "booking_form": BookingForm(data={
                    'booking_name': booking.booking_name,
                    'car_model': booking.car_model,
                    'notes': booking.notes,
                    'start_booking_date': booking.start_booking_date,
                    'end_booking_date': booking.end_booking_date}),
                "booking_id": booking.id
            },
        )

    def post(self, request, *args, **kwargs):
        try:
            print("booking_id: ", request.POST)
            booking_id_to_delete = request.POST['booking_id']
            data = get_object_or_404(Booking, id=booking_id_to_delete)
            data.delete()
        except Exception as e:
            print('%s' % e)

        queryset = User.objects.filter(username=request.user.username)
        user = get_object_or_404(queryset)

        booking_form = BookingForm(data=request.POST)

        if booking_form.is_valid():
            booking_form.instance.email = request.user.email
            booking_form.instance.name = request.user.username

            booking = booking_form.save(commit=False)
            booking.author = user

            booking.save()
        else:
            booking_form = BookingForm()

        messages.success(request, 'Your booking has been saved correctly and is awaiting approval')

        return render(
            request,
            "booking_edition.html",
            {
                "booking_form": BookingForm(data=request.POST),
                "booking_id": booking.id
            },
        )


def delete_booking(request, booking_id):
    """
    Method to handle the remove booking request
    """
    data = get_object_or_404(Booking, id=booking_id)
    data.delete()
    messages.success(request, f'Successfully removed booking: {data.booking_name}')
    return redirect('home')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>Parking Space App</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">MyCarParking</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                {% if user.username %}
                <span class="navbar-text text-muted">
                    {{user.username}}
                </span>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 bg-dark text-center">
        <span class="m-2 text-white">Julian Amigo Frances</span>
        <span class="m-2 text-white">|</span>
        <span class="m-2 text-white">julamifra@gmail.com</span>
    </footer>

    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 2500);
    </script>
</body>

</html>

templates/booking_creation.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container">
  <div class="row">
    <div class="col-md-8 mt-3 offset-md-2">
      <h3>Make a booking:</h3>
    </div>
  </div>
  <div class="row">
    <div class="row">
      <div class="col-md-8 mt-3 offset-md-2">

        {% if user.is_authenticated %}

        <p><strong>Username: </strong> {{ user.username }}</p>
        <form method="post" style="margin-top: 1.3em;">
          {{ booking_form | crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-secondary btn-lg mt-3">Submit</button>
        </form>
        {% else %}
        <h5>In order to make a booking you must be logged in. </h5>
        <p>If you have not created an account yet, then please sign up first.
        </p>
        {% endif %}

      </div>
    </div>
  </div>

</div>

{% endblock %}

templates/booking_edition.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container">
  <div class="row">
    <div class="col-md-8 mt-3 offset-md-2">
      <h3>Edit booking:</h3>
    </div>
  </div>
  <div class="row">
    <div class="row">
      <div class="col-md-8 mt-3 offset-md-2">

        {% if user.is_authenticated %}

        <p><strong>Username: </strong> {{ user.username }}</p>
        <form method="post" style="margin-top: 1.3em;">
          {{ booking_form | crispy }}
          {% csrf_token %}
          <input type="hidden" id="booking_id" name="booking_id" value="{{booking_id}}">
          <div>
            <button type="submit" class="btn btn-secondary btn-lg mt-3" >Edit</button>
            <a href="{% url 'delete_booking' booking_id %}">
              <button type="button" class="btn btn-danger btn-lg mt-3 float-end">Delete</button>
            </a>
          </div>
        </form>
        {% else %}
        <h5>In order to make a booking you must be logged in. </h5>
        <p>If you have not created an account yet, then please sign up first.
        </p>
        {% endif %}

      </div>
      
    </div>
  </div>

</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-5">
    
    {% if user.is_authenticated %}
    <div class="m-2 mx-auto">
        <a href="{% url 'booking_creation' %}" class="btn btn-outline-dark" role="button" aria-pressed="true">Make a booking</a>
    </div>

    {% if booking_list %}
    
    <!-- Booking List -->
    {% for booking in booking_list %}
    <div class="list-group">
        <a href="{% url 'booking_edition' booking.id %}" class="list-group-item list-group-item-action flex-column align-items-start mb-2">
            <div class="row">
                <div class="d-flex w-100 justify-content-between">
                    <div class="col-4 left">
                        <p class="mb-1 text-truncate" title="{{booking.booking_name}}"><strong>{{ booking.booking_name }}</strong>: <span> by {{ booking.author.username }}</span></p>
                    </div>
                    <div class="col-4 left">
                        <small><i class="far fa-calendar-check"></i> start: <i>{{ booking.start_booking_date}}</i></small>
                    </div>
                    <div class="col-4 left">
                        <small><i class="far fa-calendar-times"></i> end: <i>{{ booking.end_booking_date}}</i></small>
                    </div>
                </div>
            </div>
            <p class="mb-1 text-truncate" title="{{booking.notes}}"><i>{{ booking.notes }}</i></p>
            <div class="row">
                <div class="col-8 left text-truncate" title="{{booking.car_model}}">
                    <small ><i class="fas fa-car"></i> model: <i>{{ booking.car_model }}</i></small>
                </div>
                <div class="col-4 left">
                    <div>
                        <div class="d-inline">
                            Approved: 
                        </div> 
                        <div class="d-inline">
                            {% if booking.approved %}
                            <i class="fas fa-check-square"></i>
                            {% else %}
                            <i class="fas fa-spinner"></i>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
    
    {% else %}
    <p>You don't have any booking yet.</p>
    {% endif %}


    {% else %}
    <div>
        <h5>
            Welcome to My Personal Car Parking website. 
        </h5>
        <p>
            If you'd like to make a reservation for my parking, you must have an acocunt.
        </p>
        <p>
            <i class="fas fa-sign-in-alt"></i> If you already have an account, then please sign in here: <a class="badge badge-dark bg-dark p-2" href="{% url 'account_login' %}">Login</a>
        </p>
        <p>
            <i class="fas fa-user-plus"></i> Otherwise, you can create an account by filling out the following form: <a class="badge badge-dark bg-dark p-2" href="{% url 'account_signup' %}">Register</a>
        </p>
    </div>
    {% endif %}
</div>
{%endblock%}